version: '3'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "executable arg"]
      interval: "1m30s"
      timeout: "30s"
      retries: 5
      start_period: "30s"

  airflowpython-docker:
    image: airflowpython-docker:latest

    volumes:
      - ./airflow:/opt/airflow

    ports:
     - "8080:8080"

    command: airflow standalone